# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eba321917123b4704be144dafb002b5f7c4072de455af36d982f44cefd21543c528b3883e9fbab74d4a312b85c674b69759cac96d8ec382ca70214f699b3ff6

test:
  secret_key_base: b0ca2285bb0b989433fe4daad933f9ae50c1c8a8733980adbe022b79115ccdc94861c2e28118366c6e53a19081c2b52778d8ef9c9a8947548d3e3c80f9f6c3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
